CREATE TABLE IF NOT EXISTS Users (
    Id VARCHAR(255) PRIMARY KEY,
    Nome VARCHAR(255),
    Nascimento VARCHAR(255),
    Apelido VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS Skills (
    Skill VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS UserSkills (
    UserID VARCHAR(255),
    Skill VARCHAR(255),
    PRIMARY KEY (UserID, Skill),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (Skill) REFERENCES Skills(Skill) ON DELETE CASCADE
);
